name: tests

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    testingTest:
        runs-on: ubuntu-latest
    
        steps:
            - name: Step One 
              run: echo 'hello :)'