name: tests

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    testingTest:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 22.14

            - name: Install dependencies
              run: npm ci

            - name: Start server and run tests
              run: |
                npm start & 
                sleep 5
                npm test