name: tests

on:
    push:
        branches:
            - 'main'
    pull_request:
        branches:
            - 'main'

jobs:
    testingTest:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 22.14

            - name: Install dependancies
              run: npm ci

            - name: Run ESLint
              run: npm run lint
            
            - name: Run Stylelint
              run: npm run lint:css

            - name: Run tests
              run: npm test