name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  testingTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14

      - name: Install dependencies
        run: npm ci

      - name: Start ollama
        run: |
          $env:OLLAMA_HOST="127.0.0.1:3000"
          ollama serve &
          sleep 20

      - name: Start dotnet backend
        run: |
          cd dotnet-backend
          dotnet run & 
          sleep 20

      - name: Start Electron app
        run: |
          cd electron-app
          npm run start & 
          sleep 20

      - name: Run tests
        run: npm test